permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Oh Sheet!"
  description: |
    A bedding company with a target demographic of young, hip individuals, interested in quality bedding.
  font_url: "https://use.typekit.net/aaf3xpe.css"
  rationales:
    typefaces.primary: |
      Quicksand was chosen because it is a clean, rounded sans-serif that brings a youthful look to the site. Quicksand is to be used for all body copy and most situations.
    typefaces.secondary: |
      Benton Modern Display was chosen to contrast Quicksand since it is a modern serif font with high-contrast. Benton Modern Display is only to be used for top-level headings (i.e. the heading of a page or a section).
    colors.primary: |
      The primary colours represent a cool and clean environment. The primary navy should be used for button backgrounds and text on a white background. The primary light should be used as a background for sections and some buttons in their inactive state (i.e. the buttons for size of the sheets are primary light when they are inactive and primary what a button is selected).
    colors.secondary: |
      The secondary colours are warmer and are used for the toolbar above the navigation, some buttons, and as an accent colour for the stars for the review section of each product.
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the websites primary header & footer.
collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
