title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      This is a general purpose button that is used in all situations that are not specified in other button type descriptions. It should always be used in front of light backgrounds.
    fields:
      - name: text
        type: string
        example: "Find out more"
      - name: url
        type: url
        example: "/"
  light:
    title: "Light"
    description: |
      This button is used for the homepage banner call-to-action, as well as Add to Cart and Checkout functions. It should always be used on a white background.
    fields:
      - name: text
        type: string
        example: "Add to Cart"
      - name: url
        type: url
        example: "/"
