title: "Cards"
description: |
  Cards are used whenever there are images displayed.

patterns:
  featured-products-card:
    title: "Featured Products Card"
    description: |
      This card is used on the homepage in a section that shows only 3 cards, each with a different type of sheet.
    width: "20em"
  bedding-page-card:
    title: "Bedding Page Card"
    description: |
      This card is used on the product list page (i.e. Bedding) to display all the types of products available. These cards are displayed in a grid with no more than 4 cards in a row at large screen sizes.
    width: "16em"
  product-details-card:
    title: "Product Details Card"
    description: |
      This card is used on the product details page (i.e. when a specific product is clicked from the product list page or from the featured products on the homepage).
  review:
    title: "Review"
    description: |
      This card is used on the product details page and shows reviews for the specific product. This is only used on product detail pages.
    fields:
      - name: name
        type: string
        example: "Rebecca"
      - name: review
        type: string
        example: "This is the most comfortable bedsheet I’ve ever slept in! I’ve already ordered two more sets."
      - name: rating
        type: string
        example: "★★★★☆"
  review-small:
    title: "Review Small"
    description: |
      This card is used on the homepage in a section that houses quick links to reviews. This is only used on the homepage in a set of three.
    width: 14em;
    fields:
      - name: name
        type: string
        example: "Rebecca"
      - name: review
        type: string
        example: "This is the most comfortable bedsheet I’ve ever slept in! I’ve already ordered two more sets."
      - name: rating
        type: string
        example: "★★★★☆"
